CC    =	g++

SOURCE=edge.cpp node.cpp rrs.cpp suffixtree.cpp occurrences.cpp int_list_entry.cpp int_list.cpp repeat.cpp tandem_repeats.cpp timer.cpp

SOURCE1=rle.cpp timer.cpp

all: rrs

rrs:	${SOURCE}
	${CC} ${FLAG} -o $@ ${SOURCE} 

clean: 
	rm rrs
